default_language_version:
  python: python3

fail_fast: true

minimum_pre_commit_version: "1.14.0"

repos:
  # lint reST-files
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint
  - repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
  # require some attributes in the content files
  - repo: local
    hooks:
      - id: content_summary
        name: All articles must have a summary
        language: pygrep
        entry: ":summary:"
        args: [--negate]
        files: ^content/
        exclude: (index|404).rst|.gitkeep
      - id: content_keywords
        name: All articles must have keywords
        language: pygrep
        entry: ":keywords:"
        args: [--negate]
        files: ^content/
        exclude: (index|404).rst|.gitkeep
  # prettier (formatting for various file types)
  - repo: local
    hooks:
      - id: prettier
        name: Run prettier
        entry: npx prettier --write --ignore-unknown
        language: system
        args: []
        "types": [text]
  # black (Python: code formatting)
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  # isort (Python: automatically sort import statements)
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  # flake8 (linting)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          # https://github.com/PyCQA/flake8-bugbear
          - flake8-bugbear
          # https://github.com/adamchainz/flake8-comprehensions
          - flake8-comprehensions
          # https://github.com/PyCQA/flake8-docstrings
          - flake8-docstrings
          # https://github.com/globality-corp/flake8-logging-format
          - flake8-logging-format
  # lint templates
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-jinja
        files: ^theme/mischback/
        types_or: ["html"]
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        files: ^theme/mischback/
        types_or: ["html"]
  # lint SASS
  - repo: local
    hooks:
      - id: stylelint
        name: Run stylelint
        entry: npx stylelint
        language: system
        args: [--fix]
        files: ^theme/mischback/_src/style/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # check scripts to have shebangs
      - id: check-executables-have-shebangs
      # check JSON files
      - id: check-json
      # check TOML files
      - id: check-toml
      # check YAML files
      - id: check-yaml
      # check links to GitHub
      - id: check-vcs-permalinks
      # let all files end with a single new line (this *should be ensured by
      # .editorconfig already)
      - id: end-of-file-fixer
      # remove all trailing whitespaces (this *should* be ensured by
      # .editorconfig already)
      - id: trailing-whitespace
      # provide uniform line endings for the project ('lf'; this *should be
      # ensured by .editorconfig already)
      - id: mixed-line-ending
        args: [--fix, lf]
      # remove utf-8 byte order marker
      - id: fix-byte-order-marker
