default_language_version:
  python: python3

fail_fast: true

minimum_pre_commit_version: '1.14.0'

repos:
  # lint rST-files
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.6.7
    hooks:
      - id: sphinx-lint
  - repo: https://github.com/pycqa/doc8
    rev: 0.10.1
    hooks:
      - id: doc8
  # black (Python: code formatting)
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  # isort (Python: automatically sort import statements)
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  # flake8 (linting)
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-docstrings, flake8-logging-format]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # check scripts to have shebangs
      - id: check-executables-have-shebangs
      # check JSON files
      - id: check-json
      # check TOML files
      - id: check-toml
      # check YAML files
      - id: check-yaml
      # check links to GitHub
      - id: check-vcs-permalinks
      # let all files end with a single new line (this *should be ensured by
      # .editorconfig already)
      - id: end-of-file-fixer
      # remove all trailing whitespaces (this *should* be ensured by
      # .editorconfig already)
      - id: trailing-whitespace
      # provide uniform line endings for the project ('lf'; this *should be
      # ensured by .editorconfig already)
      - id: mixed-line-ending
        args: [--fix, lf]
      # remove utf-8 byte order marker
      - id: fix-byte-order-marker
