extends:
  - stylelint-config-standard-scss
  - stylelint-config-sass-guidelines
  - stylelint-config-property-sort-order-smacss

rules:
  color-function-notation: "modern"
  scss/no-global-function-names: null
