extends:
  - stylelint-config-standard-scss
  - stylelint-config-sass-guidelines
  - stylelint-config-property-sort-order-smacss
  - stylelint-config-prettier

rules:
  color-function-notation: "legacy"
  indentation: 2
