extends:
  - stylelint-config-standard-scss
  - stylelint-config-sass-guidelines
  - stylelint-config-property-sort-order-smacss
  - stylelint-config-prettier

rules:
  indentation: 2
  selector-max-id: 2
