# ### tox configuration
[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.26.0

[testenv:build-sphinx]
basepython = python3
deps =
  -r {toxinidir}/requirements/build-sphinx.txt
envdir = {toxworkdir}/build-sphinx
setenv =
  PYTHONDONTWRITEBYTECODE=1
skip_install = true
commands =
  {posargs:sphinx-build -b dirhtml -c ./ "content" ".build"}

[testenv:build-serve]
basepython = {[testenv:build-sphinx]basepython}
changedir = {toxinidir}/.build
deps = {[testenv:build-sphinx]deps}
envdir = {[testenv:build-sphinx]envdir}
setenv = {[testenv:build-sphinx]setenv}
skip_install = {[testenv:build-sphinx]skip_install}
commands =
  python -m http.server {posargs:8082}

[testenv:pre-commit]
basepython = python3
deps =
  -r {toxinidir}/requirements/pre-commit.txt
envdir = {toxworkdir}/pre-commit
setenv =
  PYTHONDONTWRITEBYTECODE=1
passenv = SSH_AUTH_SOCK
skip_install = true
commands =
  {posargs:pre-commit run}

[testenv:pip-tools]
basepython = python3
deps =
  -r {toxinidir}/requirements/pip-tools.txt
envdir = {toxworkdir}/pip-tools
setenv =
  PYTHONDONTWRITEBYTECODE=1
skip_install = true
commands =
  pip-compile --resolver=backtracking {posargs}
"""
