name: CI Default Branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  # evaluation:
  #   name: Evaluate GitHub's IPv6
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Ping mischback.de
  #       run: ping -6 mischback.de
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  building:
    name: Build with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache build environment
        id: cache-tox
        uses: actions/cache@v4
        with:
          path: |
            .tox
            .tox-venv
            .npm
            ${{ env.pythonLocation }}
          key: build-${{ hashFiles( env.pythonLocation, 'requirements/tox.txt', 'requirements/sphinx.txt', 'requirements/post-processing.txt', 'pyproject.toml', 'package.json', 'package-lock.json') }}
      - name: Run Sphinx's linkcheck
        run: make util/lint/sphinx-linkcheck
      - name: Build HTML output
        run: make build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: .build/
          if-no-files-found: error
          retention-days: 1

  validation:
    needs: building
    name: Validate build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_output
          path: build/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html5validator
          npm --prefix util/ci/validation install htmlhint html-validate
      - name: Run html5validator
        run: |
          html5validator --root build/ --also-check-css --also-check-svg --show-warnings \
            --ignore \
              "Consider using the \"h1\" element as a top-level heading only" \
              "Consider using \"h2\"-\"h6\" elements to add identifying headings to all" \
              "is not a \"font-stretch\" value" \
              "is not a \"text-decoration\" value" \
              "Property \"text-underline-offset\" doesn't exist" \
              "Attribute \"aria-hidden\" is unnecessary for elements that have attribute \"hidden\""
      - name: Run htmlhint
        run: npm --prefix util/ci/validation exec -- htmlhint "./build/**/*.html" --config "./util/ci/htmlhint.conf"
      - name: Run html-validate
        run: npm --prefix util/ci/validation exec -- html-validate "./build/**/*.html" --config "./util/ci/html-validate.json"
      - name: Run html-proofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: ./build
          # FIXME: Activate this as soon as there is a favicon!
          check_favicon: false
          # FIXME: #61
          check_images: false
          # External links are checked by Sphinx's linkcheck already
          disable_external: true
          enforce_https: false
          ignore_urls: ""
          swap_urls: ""

  dependabot:
    needs: [linting, building]
    uses: mischback/development-meta/.github/workflows/dependabot-auto-approve.yml@development
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
