name: CI Default Branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  building:
    name: Build with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actiosn/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/build-sphinx.txt
      - name: Build HTML output
        run: sphinx-build -b dirhtml -c ./ "content" ".build"

  dependabot:
    needs: linting, building
    uses: mischback/development-meta/.github/workflows/dependabot-auto-approve.yml@development
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
