
name: CI Default Branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  dependabot:
    uses: mischback/development-meta/.github/workflows/dependabot-auto-approve.yml@development
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
