name: CI Default Branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/pre-commit.txt
      - name: Lint reST files
        run: |
          make util/lint/sphinx-lint
          make util/lint/doc8
          make util/lint/content/summary
          make util/lint/content/keywords
      - name: Lint templates
        run: |
          make util/lint/djlint
          make util/lint/curlylint
      - name: Prettier
        run: make util/lint/prettier
      - name: Lint Python files
        run: |
          make util/lint/black
          make util/lint/isort
          make util/lint/flake8
  dependabot:
    uses: mischback/development-meta/.github/workflows/dependabot-auto-approve.yml@development
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
